
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

module "ollama-template" {
  source               = "github.com/terraform-google-modules/terraform-google-vm//modules/instance_template?ref=v15.0.0"
  project_id           = "buildgrid-498300"
  region               = "us-central1"
  name_prefix          = "ollama-template"
  machine_type         = "g2-standard-24"
  on_host_maintenance  = "TERMINATE"
  source_image_family  = "common-cu129-ubuntu-2204-nvidia-580"
  source_image_project = "deeplearning-platform-release"
  network              = "default"
  startup_script       = "#!/bin/bash\ncurl -fsSL https://ollama.com/install.sh | sh\nollama serve &\nsleep 10\nollama pull llama3.1\nollama pull llama3.2-vision\napt-get update && apt-get install -y ffmpeg\npip3 install -U openai-whisper"
  access_config = [
    {
      nat_ip       = null
      network_tier = "PREMIUM"
    },
  ]
  gpu = {
    count = 2
    type  = "nvidia-l4"
  }
}
module "ollama-vm" {
  source            = "github.com/terraform-google-modules/terraform-google-vm//modules/compute_instance?ref=v15.2.0"
  project_id        = "buildgrid-498300"
  hostname          = "ollama-vm"
  instance_template = module.ollama-template.self_link
  region            = "us-central1"
}
