
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

output "ollama-template_network_interface_details" {
  description = "The names and VLAN tags of the template interfaces."
  value       = module.ollama-template.network_interface_details
}
