
# This file is autogenerated. Do not edit this file directly.
# Please make changes to the application template instead.
# Application Template: projects/default-project/locations/us-central1/spaces/default-space/applicationTemplates/default-app-template

provider "google" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  project                     = "buildgrid-498300"
  region                      = "us-central1"
}

provider "google-beta" {
  default_labels = {
    goog-adc-tf-deployment = "export"
  }
  project                     = "buildgrid-498300"
  region                      = "us-central1"
}
